/* fuckmem.c :: TODO document
 *
 *
 *
 */

/* homemade inclusions */
#include "fuckmem.h"

/* c standard inclusions */
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>

#define MINALLOC 1024 /* the minimum number of units to request from the system */
#define RANGE 4 /* range of randomness in fuckmem */

/* static variables */
static Header base; /* an empty list to start building the "free list" */
static Header *freep = NULL; /* start of the free list, starts as Null. stands for free pointer
                                If Null free list has yet to be started */



void *fuckmem(unsigned num_bytes){
       
    /* p stands for pointer, it is the current pointer to the free list freep
     * prevp stands for previous pointer, it lets us keep track of where we just came from on the free list
     */
    Header *p, *prevp;
    
    /* sets prevp equal to freep */
    prevp = freep;

    /* this if statement only runs if the free list has not yet been made */
    if ( freep == NULL ){
        srand(time(NULL)); /* sets random seed based on time */
        base.s.ptr = freep = prevp = &base;
        base.s.size = 0;
        /* starts off with an empty free list pointing at itself */
    }

    /* nunits is the number of Header units we are returning, calculated here poorly ON PURPOSE */
    unsigned nunits;
    nunits = (  (  num_bytes + sizeof(Header) - 1  )/sizeof(Header)  ) +  (((rand() % RANGE) + 1 ) -  ((rand() % RANGE) + 1 ) );
    
    /* pre : sets pointer to prevp which has ben set to freep, the start of the free list
     * check : nothing
     * post : sets prevp to p, and p to the next header on the free list 
     */
    for ( p = prevp->s.ptr; ; prevp = p, p = p->s.ptr) { /* middle left blank on purpose, should return in loop */
        
        /* checks if the current memory header is big enough */
        if ( p->s.size >= nunits ) {

            /* for exactly enough memory */
            if (p->s.size  == nunits){
                prevp->s.ptr = p->s.ptr; /* removes p from the free list */
            } else{
                /* if too much memory in p, use the end of p */
                p->s.size -= nunits; 

                p += p->s.size; /* changes what p points to, makes it at the tail end */
                p->s.size = nunits + ( ((rand() % RANGE) + 1) - ((rand() % RANGE) + 1) );
            }

            freep = prevp;
            return (void *)(p+1); /* plus 1 because the header is right before the block of memory */
        }
     

        /* if statement is true if p hits freep (begining of free list)
         * this means we have checked the whole free list for a chunk big enough, and failed to find one
         */
        if  ( p == freep){
            p = moremem(nunits);
            if( p == NULL){
                return NULL; /* no memory left :( */
            }
        }
    }
}


static Header *moremem(unsigned num_units){
    
    /* charachter_p stands for character pointer, it will hold the pointer generated by the linux system through
     * the sbrk system call */
    char *character_p;
    
    /* tp stands for temp pointer, it will hold the requested size, then have it be freed into the free list */
    Header *tp;

    /* makes sure that a block of at lease MINALLOC is being allocated */
    if( num_units < MINALLOC )
        num_units = MINALLOC;
    
    /* the request of bytes from the linux system */
    character_p = sbrk( num_units * sizeof(Header) );

    if( character_p == (char *) -1)
        return NULL;
    
    tp = (Header *) character_p;
    tp->s.size = num_units;

    /* frees the allocated memory into the free list */
    freeish((void *) (tp+1));

    return freep;   
}


void freeish(void *to_free){
    Header *blockp, *p;

    /* */
    blockp = (Header *)to_free - 1; 
    
    /* pre : set p = freep
     * check : block pointer is not larger than p and block pointer is not smaller than p->s.ptr
     * post : p goes to the next pointer
     */
    for(p = freep; !(blockp > p && blockp < p->s.ptr) ; p = p->s.ptr){
        if ( p >= p->s.ptr && (blockp > p || blockp < p->s.ptr))
            break; /* freed block at start or end of arena */
    }


    if (blockp + blockp->s.size == p->s.ptr) { /* join to upper nbr */
        blockp->s.size += p->s.ptr->s.size;
        blockp->s.ptr = p->s.ptr->s.ptr;
    } else{
        blockp->s.ptr = p->s.ptr;
    }
    
    if (p + p->s.size == blockp) { /* join to lower nbr */
        p->s.size += blockp->s.size;
        p->s.ptr = blockp->s.ptr;
    } else {
        p->s.ptr = blockp;
    }
    

    freep = p;
}




